/* config.h.  Generated by configure.  */
/*
 *	Copyright (c) 2004 Rinet Corp., Novosibirsk, Russia
 *
 * Redistribution and use in source forms, with and without modification,
 * are permitted provided that this entire comment appears intact.
 * Redistribution in binary form may occur without any restrictions.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' WITHOUT ANY WARRANTIES OF ANY KIND.
 */

#ifndef	_CONFIG_H_
#define	_CONFIG_H_

/*
 * This file contain compile-time options and system-depended definitions.
 * Please edit config.h after `./configure' before `make' (if required).
 */

/*
 * The curses library definition.
 */

/* Define if you have the slang curses library (-lslang) */
//#define HAVE_SLCURSES 1

/* Define if you have the ncurses library (-lncurses) */
#define HAVE_NCURSES 1

/* Define if you have the curses library (-lcurses) */
/* #undef HAVE_CURSES */

/* Define if your curses has a colors functions such as
   has_colors(), start_color(), init_pair(), and so on */
#define HAVE_HAS_COLORS 1

/* Define if your curses has the bkgd() function */
#define HAVE_BKGD 1

/* Define if your curses has the wbkgd() function */
#define HAVE_WBKGD 1

/* Define if your curses has the wredrawln() function */
#define HAVE_WREDRAWLN 1

/* Define if your curses has the resizeterm() function */
#define HAVE_RESIZETERM 1

/* Define if your curses has the use_default_colors() function */
#define HAVE_USE_DEFAULT_COLORS 1

/*
 * System-depended definition.
 */

/* Define to `unsigned char' if <sys/types.h> doesn't define */
/* #undef u_int8_t */

/* Define to `unsigned short' if <sys/types.h> doesn't define */
/* #undef u_int16_t */

/* Define to `unsigned int' if <sys/types.h> doesn't define */
/* #undef u_int32_t */

/* Define to `unsigned long long' if <sys/types.h> doesn't define */
/* #undef u_int64_t */

/* Define to `unsigned int' if <sys/types.h> doesn't define */
/* #undef in_addr_t */

/* Define to `int' if <sys/types.h> or <sys/socket.h> doesn't define */
/* #undef socklen_t */

/* Define if <sys/socket.h> has declared `struct sockaddr_storage' */
#define HAVE_SOCKADDR_STORAGE 1

/* Define if <netinet/if_ether.h> has declared `struct ether_addr' */
#define HAVE_ETHER_ADDR 1

/* Define if your libpcap has the pcap_dump_flush() function */
#define HAVE_PCAP_DUMP_FLUSH 1

/* Define if your libpcap has the pcap_get_selectable_fd() function */
#define HAVE_PCAP_GET_SELECTABLE_FD 1

/* Define if you have the siginterrupt() function */
#define HAVE_SIGINTERRUPT 1

/* Define if you have the strcasecmp() function */
#define HAVE_STRCASECMP 1

/* Define if you have the strftime() function */
#define HAVE_STRFTIME 1

/* Define if you have POSIX threads libraries and header files */
#define HAVE_PTHREAD 1

/* Define if you have the <sys/termios.h> header file */
#define HAVE_SYS_TERMIOS_H 1

/* Define if you have the <net/if_dl.h> header file */
#define HAVE_NET_IF_DL_H 1

/* Define if you have the <resolv.h> header file */
#define HAVE_RESOLV_H 1

/* Define to empty if the keyword does not work */
/* #undef const */

/* fake for osf */
/* #undef __STDC__ */

// add by dove
#include <net/if_ether.h>
static char package[] = "trafshow";
static char version[] = "5.2.3";
static char target[] = "arm-android";
static char compiled[] = "porting by dove.";

#endif	/* !_CONFIG_H */
